Repository FF12-Modding/FF12-MO2-Plugin, pull requests merged in 2025-08, with the labels that each got.

#2 Fix release template
  .github/changelog-config.json
  game_ff12.py
Labels: fix

#3 Update readme with new information
  README.md
Labels: documentation

#4 Split modules
  ff12/DateHelper.py
  ff12/ModDataChecker.py
  ff12/SaveGame.py
  ff12/SteamHelper.py
  game_ff12.py
Labels: refactor
